version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: 'redis://redis:6379/0'
      SERVER_URL: 'http://0.0.0.0:8000'
    volumes:
      - '.:/opt/app'

  redis:
    image: 'redis:6'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
